"""add_exam_type_and_total_weight_fields

Revision ID: 10e51f0310a9
Revises: 865c86795d47
Create Date: 2026-03-18 18:43:42.573071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10e51f0310a9'
down_revision: Union[str, None] = '865c86795d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ENUM type first
    sa.Enum('CUSTOM', 'DIAGNOSTIC', 'MIDTERM', 'FINAL', name='examtype').create(op.get_bind(), checkfirst=True)
    
    op.add_column('exam_records', sa.Column('exam_type', sa.Enum('CUSTOM', 'DIAGNOSTIC', 'MIDTERM', 'FINAL', name='examtype'), nullable=False, server_default='CUSTOM'))
    op.add_column('user_knowledge_mastery', sa.Column('total_weight', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_knowledge_mastery', 'total_weight')
    op.drop_column('exam_records', 'exam_type')
    # ### end Alembic commands ###
