"""Add GeminiToken model

Revision ID: 30d5f61b81bc
Revises: ba322e737db5
Create Date: 2026-03-02 16:38:44.682937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d5f61b81bc'
down_revision: Union[str, None] = 'ba322e737db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gemini_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gemini_tokens_id'), 'gemini_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_gemini_tokens_name'), 'gemini_tokens', ['name'], unique=True)
    op.drop_index(op.f('path_gist_idx'), table_name='knowledge_nodes', postgresql_using='gist')
    op.drop_index(op.f('path_idx'), table_name='knowledge_nodes')
    op.create_index(op.f('ix_knowledge_nodes_id'), 'knowledge_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_path'), 'knowledge_nodes', ['path'], unique=False)
    op.create_index(op.f('ix_practice_problems_id'), 'practice_problems', ['id'], unique=False)
    op.create_index(op.f('ix_practice_problems_knowledge_path'), 'practice_problems', ['knowledge_path'], unique=False)
    op.create_foreign_key(None, 'problems', 'problems', ['source_problem_id'], ['id'])
    op.create_index(op.f('ix_solution_attempts_id'), 'solution_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_weekly_reports_id'), 'weekly_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_reports_id'), table_name='weekly_reports')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_index(op.f('ix_solution_attempts_id'), table_name='solution_attempts')
    op.drop_constraint(None, 'problems', type_='foreignkey')
    op.drop_index(op.f('ix_practice_problems_knowledge_path'), table_name='practice_problems')
    op.drop_index(op.f('ix_practice_problems_id'), table_name='practice_problems')
    op.drop_index(op.f('ix_knowledge_nodes_path'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_id'), table_name='knowledge_nodes')
    op.create_index(op.f('path_idx'), 'knowledge_nodes', ['path'], unique=False)
    op.create_index(op.f('path_gist_idx'), 'knowledge_nodes', ['path'], unique=False, postgresql_using='gist')
    op.drop_index(op.f('ix_gemini_tokens_name'), table_name='gemini_tokens')
    op.drop_index(op.f('ix_gemini_tokens_id'), table_name='gemini_tokens')
    op.drop_table('gemini_tokens')
    # ### end Alembic commands ###
