"""add_paper_exam_fields_to_assessment_session

Revision ID: 39f2ab49eb08
Revises: e7ca73402ff7
Create Date: 2026-03-16 17:04:31.638891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39f2ab49eb08'
down_revision: Union[str, None] = 'e7ca73402ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_sessions', sa.Column('paper_snapshot', sa.JSON(), nullable=True))
    op.add_column('assessment_sessions', sa.Column('paper_image_paths', sa.JSON(), nullable=True))
    op.add_column('assessment_sessions', sa.Column('graded_problems', sa.JSON(), nullable=True))
    op.add_column('assessment_sessions', sa.Column('formatting_feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_sessions', 'formatting_feedback')
    op.drop_column('assessment_sessions', 'graded_problems')
    op.drop_column('assessment_sessions', 'paper_image_paths')
    op.drop_column('assessment_sessions', 'paper_snapshot')
    # ### end Alembic commands ###
