"""Add ExamRecord and ExamProblemResult models

Revision ID: 5266b4780940
Revises: 39f2ab49eb08
Create Date: 2026-03-17 15:38:12.589112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5266b4780940'
down_revision: Union[str, None] = '39f2ab49eb08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('overall_evaluation', sa.Text(), nullable=True),
    sa.Column('image_paths', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_records_id'), 'exam_records', ['id'], unique=False)
    op.create_index(op.f('ix_exam_records_user_id'), 'exam_records', ['user_id'], unique=False)
    op.create_table('exam_problem_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('problem_number', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('knowledge_tag', sa.String(length=100), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_problem_results_exam_id'), 'exam_problem_results', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_problem_results_id'), 'exam_problem_results', ['id'], unique=False)
    op.create_index(op.f('ix_exam_problem_results_knowledge_tag'), 'exam_problem_results', ['knowledge_tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_problem_results_knowledge_tag'), table_name='exam_problem_results')
    op.drop_index(op.f('ix_exam_problem_results_id'), table_name='exam_problem_results')
    op.drop_index(op.f('ix_exam_problem_results_exam_id'), table_name='exam_problem_results')
    op.drop_table('exam_problem_results')
    op.drop_index(op.f('ix_exam_records_user_id'), table_name='exam_records')
    op.drop_index(op.f('ix_exam_records_id'), table_name='exam_records')
    op.drop_table('exam_records')
    # ### end Alembic commands ###
