"""exam: add image_urls and per-problem ocr fields

Revision ID: 865c86795d47
Revises: ada8927bda94
Create Date: 2026-03-17 18:03:06.017807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '865c86795d47'
down_revision: Union[str, None] = 'ada8927bda94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_problem_results', sa.Column('original_question_text', sa.Text(), nullable=True))
    op.add_column('exam_problem_results', sa.Column('user_answer_text', sa.Text(), nullable=True))
    op.add_column('exam_records', sa.Column('image_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_records', 'image_urls')
    op.drop_column('exam_problem_results', 'user_answer_text')
    op.drop_column('exam_problem_results', 'original_question_text')
    # ### end Alembic commands ###
