"""add exam paper_name and ai_model

Revision ID: ada8927bda94
Revises: 5266b4780940
Create Date: 2026-03-17 17:40:01.597735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ada8927bda94'
down_revision: Union[str, None] = '5266b4780940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_records', sa.Column('paper_name', sa.String(length=255), nullable=True))
    op.add_column('exam_records', sa.Column('ai_model', sa.String(length=100), nullable=True))
    op.add_column('exam_records', sa.Column('overall_feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_records', 'overall_feedback')
    op.drop_column('exam_records', 'ai_model')
    op.drop_column('exam_records', 'paper_name')
    # ### end Alembic commands ###
