"""Add DailyReview table

Revision ID: b32b924f1c19
Revises: bf73e4ac47b1
Create Date: 2026-03-11 14:04:38.242183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32b924f1c19'
down_revision: Union[str, None] = 'bf73e4ac47b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('problem_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_reviews_id'), 'daily_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_daily_reviews_review_date'), 'daily_reviews', ['review_date'], unique=False)
    op.drop_index(op.f('idx_api_call_logs_created_at'), table_name='api_call_logs')
    op.create_index(op.f('ix_api_call_logs_id'), 'api_call_logs', ['id'], unique=False)
    op.create_index(op.f('ix_practice_sessions_id'), 'practice_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_sessions_id'), table_name='practice_sessions')
    op.drop_index(op.f('ix_api_call_logs_id'), table_name='api_call_logs')
    op.create_index(op.f('idx_api_call_logs_created_at'), 'api_call_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_daily_reviews_review_date'), table_name='daily_reviews')
    op.drop_index(op.f('ix_daily_reviews_id'), table_name='daily_reviews')
    op.drop_table('daily_reviews')
    # ### end Alembic commands ###
