"""Add ModelConfig table

Revision ID: bf73e4ac47b1
Revises: 30d5f61b81bc
Create Date: 2026-03-02 17:23:02.953463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf73e4ac47b1'
down_revision: Union[str, None] = '30d5f61b81bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_configs_id'), 'model_configs', ['id'], unique=False)
    op.create_index(op.f('ix_model_configs_role'), 'model_configs', ['role'], unique=True)
    
    # Insert default model configs
    op.execute(
        """
        INSERT INTO model_configs (role, model_name, description, updated_at) 
        VALUES 
            ('vision', 'gemini-2.0-flash', 'Default model for image recognition and OCR processing', NOW()),
            ('teaching', 'gemini-2.0-pro', 'High-accuracy intelligence model for complex reasoning and mathematical solving', NOW()),
            ('utility', 'gemini-2.0-flash-lite', 'Fast and cost-effective model for data extraction and basic tasks', NOW())
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Remove default model configs
    op.execute("DELETE FROM model_configs WHERE role IN ('vision', 'teaching', 'utility')")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_configs_role'), table_name='model_configs')
    op.drop_index(op.f('ix_model_configs_id'), table_name='model_configs')
    op.drop_table('model_configs')
    # ### end Alembic commands ###
