"""Add UserKnowledgeMastery and formatting_feedback

Revision ID: cb67840041d9
Revises: b32b924f1c19
Create Date: 2026-03-16 15:09:16.767728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb67840041d9'
down_revision: Union[str, None] = 'b32b924f1c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_knowledge_mastery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_tag', sa.String(), nullable=False),
    sa.Column('user_self_rating', sa.Float(), nullable=True),
    sa.Column('ai_assessed_rating', sa.Float(), nullable=True),
    sa.Column('comprehensive_score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_knowledge_mastery_id'), 'user_knowledge_mastery', ['id'], unique=False)
    op.create_index(op.f('ix_user_knowledge_mastery_knowledge_tag'), 'user_knowledge_mastery', ['knowledge_tag'], unique=False)
    op.create_index(op.f('ix_user_knowledge_mastery_user_id'), 'user_knowledge_mastery', ['user_id'], unique=False)
    op.add_column('solution_attempts', sa.Column('formatting_feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solution_attempts', 'formatting_feedback')
    op.drop_index(op.f('ix_user_knowledge_mastery_user_id'), table_name='user_knowledge_mastery')
    op.drop_index(op.f('ix_user_knowledge_mastery_knowledge_tag'), table_name='user_knowledge_mastery')
    op.drop_index(op.f('ix_user_knowledge_mastery_id'), table_name='user_knowledge_mastery')
    op.drop_table('user_knowledge_mastery')
    # ### end Alembic commands ###
